deploy:
  provider: pages
  skip-cleanup: true
  github-token: LYYlVMbAyobShMTBQbhJwg  # Set in travis-ci.org dashboard
  keep-history: true
#  local-dir: docs/_build/html
  committer-from-gh: true
  on:
    branch: master

#language: ruby
#rvm:
#- 2.3.3
#script: "bundle exec jekyll build"

#sudo: false # if error set "required"
