# Enables Travis to use their new container-based infrastructure
#sudo: false

#before_install:
#  - gem update --system
# This is a workaround for a problem with a specific version of bundler and rubygems
#  - gem install bundler

# Define how to run your tests (defaults to `bundle exec rake` or `rake` depending on whether you have a `Gemfile`)
#script: "bundle exec rake"

#deploy:
#  provider: pages
#  skip-cleanup: true
#  github-token: f20bcaab6223bcbff2d25fc5fa6556fbf0e6e88e  # Set in the settings page of your repository, as a secure variable
#  keep-history: true
#  on:
#    branch: master

language: ruby

script:
  - bundle exec jekyll algolia --destination _site --config _config.yml

branches:
  only:
  - backup
#  - /pages-(.*)/ # test every branch which starts with "pages-"

rvm:
- 2.4