bundler_args: --without benchmark:site:development
script: script/cibuild
cache: bundler
language: ruby

rvm:
  - 2.3.3

install:
  - bundle install
  - gem install jekyll
  - gem install jekyll-feed

branches:
  only:
  - master
  - /pages-(.*)/ # test every branch which starts with "pages-"

env:
  global:
    - JEKYLL_ENV=production
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # if error set "required"
