# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#encoding: bom|utf-8
#language: ru-ru
lang: ru

version: 3.7.0
author: Tired of sorting the bookmarks - now they will be groking here.
title: bopoh13
email: tester@example.com
##repository: bopoh13/ctc-leaflet1
description: > # this means to ignore newlines until "baseurl:"
  You can report errors in the text here.
meta_description: script, test
##baseurl: "/ctc-leaflet1" # the subpath of your site, e.g. /blog
##url: "https://bopoh13.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#layouts: _layouts
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
# Jekyll 3 now only supports Kramdown for Markdown
markdown: kramdown
timezone: Europe/Moscow

#theme: minima
plugins:
  - jekyll-feed
#  - jekyll-redirect-from

## More https://habrahabr.ru/post/336266/ and https://github.com/jekyll/jekyll/blob/master/docs/_config.yml
collections:
  posts:
    permalink: "/post/:short_year:month:day:output_ext"
    output: true

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: pages # previously `page` in Jekyll 2.2.
    values:
      layout: main

# Exclude these files from your production _site
#
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

theme: jekyll-theme-cayman